spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-g66m6-kr.vpc-pub-cdb.ntruss.com:3306/bit4final?serverTimezone=Asia/Seoul
    username: study
    password: bit4!@#$

